"""
cookie_helper.py - 浏览器 Cookie 提取模块

修复历史：
  v1 bug：按域名过滤时，Chrome 127+ 新加密方式导致解密异常被静默吞掉，
          结果返回空列表，误报"未找到 Cookie"。
  v2 fix：先提取全部 Cookie，再在本地过滤域名，解密失败有明确提示。
"""

import os
from datetime import datetime

COOKIES_DIR = "cookies"

# 抖音 / 小红书的关键域名关键字
TARGET_KEYWORDS = ["douyin", "iesdouyin", "xiaohongshu", "xhslink", "xhs"]


def extract_and_save(browser: str) -> tuple[bool, str]:
    """
    从指定浏览器提取全部 Cookie，筛选出抖音/小红书相关部分，
    保存为 Netscape 格式文件供 yt-dlp 使用。

    返回：(成功与否, 文件路径 或 错误说明)
    """
    os.makedirs(COOKIES_DIR, exist_ok=True)

    try:
        import browser_cookie3
    except ImportError:
        return False, "未安装 browser_cookie3，请运行：pip install browser-cookie3"

    browser_map = {
        "Chrome":  browser_cookie3.chrome,
        "Edge":    browser_cookie3.edge,
        "Firefox": browser_cookie3.firefox,
    }
    if browser not in browser_map:
        return False, f"不支持的浏览器：{browser}"

    loader_func = browser_map[browser]

    # ── Step 1：提取全部 Cookie（不过滤域名，避免解密失败被静默跳过）──
    try:
        jar = loader_func()
        all_cookies = list(jar)
    except PermissionError:
        return False, (
            f"无法读取 {browser} 的 Cookie 数据库（权限不足）\n\n"
            "解决方法：在任务管理器中完全结束所有 Chrome 进程后重试"
        )
    except Exception as e:
        err = str(e)
        if "database is locked" in err.lower() or "could not copy" in err.lower():
            return False, (
                f"{browser} 数据库被锁定（浏览器仍在运行）\n\n"
                "解决方法：完全关闭 Chrome 后重试，或改用「手动导出」"
            )
        # Chrome 127+ App-Bound Encryption 错误
        if "crypt" in err.lower() or "decrypt" in err.lower() or "dpapi" in err.lower():
            return False, (
                "Chrome 127+ 使用了新加密方式，当前版本 browser_cookie3 无法解密。\n\n"
                "建议方案：改用 **Edge 或 Firefox** 登录抖音后提取 Cookie\n"
                "（Edge 与 Chrome 账号体系相同，可用 Chrome 账号登录 Edge）"
            )
        return False, f"提取失败：{err}"

    if not all_cookies:
        return False, (
            f"未从 {browser} 中读取到任何 Cookie。\n\n"
            "可能原因：\n"
            "1. Chrome 版本 ≥ 127 启用了新加密，建议改用 Edge 或 Firefox\n"
            "2. 浏览器尚未有任何登录记录"
        )

    # ── Step 2：筛选抖音 / 小红书相关 Cookie ──
    target_cookies = [
        c for c in all_cookies
        if any(kw in (c.domain or "").lower() for kw in TARGET_KEYWORDS)
    ]

    if not target_cookies:
        total = len(all_cookies)
        # 列出前几个域名，帮助用户确认读的是否是正确的浏览器配置文件
        sample_domains = list({c.domain for c in all_cookies[:50] if c.domain})[:8]
        domains_hint = "、".join(sample_domains) if sample_domains else "（无）"
        return False, (
            f"从 {browser} 读取到 {total} 条 Cookie，但**没有**抖音或小红书的登录记录。\n\n"
            f"当前读取到的域名样本：{domains_hint}\n\n"
            "请确认：\n"
            "1. 你在该浏览器中已访问并登录了 **douyin.com** 或 **xiaohongshu.com**\n"
            "2. 如果使用多个 Chrome 用户配置，程序默认读取第一个（Default）配置文件，\n"
            "   建议改用只有一个配置文件的 **Edge 或 Firefox**"
        )

    # ── Step 3：保存为 Netscape 格式 ──
    output_path = os.path.join(COOKIES_DIR, f"cookies_{browser.lower()}.txt")
    _save_as_netscape(target_cookies, output_path)

    return True, output_path


def _save_as_netscape(cookies: list, output_path: str):
    """将 Cookie 对象列表写入 Netscape 格式文件"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by AutoViral AI\n")
        f.write(f"# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        for c in cookies:
            domain = c.domain or ""
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.path or "/"
            secure = "TRUE" if c.secure else "FALSE"
            expiry = int(c.expires) if c.expires else 0
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{c.name or ''}\t{c.value or ''}\n")


def get_saved_cookie_file(browser: str) -> str | None:
    """返回已保存的 Cookie 文件路径（存在且非空则返回）"""
    path = os.path.join(COOKIES_DIR, f"cookies_{browser.lower()}.txt")
    if os.path.exists(path) and os.path.getsize(path) > 200:
        return path
    return None


def get_cookie_file_mtime(browser: str) -> str:
    """返回 Cookie 文件的最后更新时间（用于 UI 显示）"""
    path = os.path.join(COOKIES_DIR, f"cookies_{browser.lower()}.txt")
    if os.path.exists(path):
        return datetime.fromtimestamp(os.path.getmtime(path)).strftime("%m-%d %H:%M")
    return ""
